version: "2"
linters:
  enable:
    - err113
    - godot
    - godox
    - gosec
    - misspell
    - nlreturn
    - nosprintfhostport
    - predeclared
    - promlinter
    - whitespace
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
        text: do not define dynamic errors, use wrapped static errors instead
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
